### ISSUE TITLE
responsive-typography question

### ISSUE THREAD

**Issue by natduboiss** [natduboiss/first-website#2]
Markbot is saying expected to see font-size in a different value and the line-height in a different value in the html in the media 38em. For the line-height i in the normal and inherit one and still nothing. How do I know what font-size and line-height to use?

@thomasjbradley

**Comment by thomasjbradley** [comment]
It doesn't look like the website has been synced, so I can't check out the code.

But, my guess would be that the numbers don’t match our `font-size` & `line-height` standards:
https://learn-the-web.algonquindesign.ca/topics/screen-sizes-cheat-sheet/

---

p.s. This issue is attached to your `first-website`, not to your `responsive-typography` project. It'd be much easier for me to have the issue attached to the right repository, that way I don't have to go digging through you account to find the code.

**Comment by natduboiss** [comment]
@thomasjbradley markbot is now saying that the margin put in the body is expected to be a different value. i tried 1.5,1.4 and 1.3rem. 
And how do i create a new issue for the responsive-typography project? sorry about that!

**Comment by thomasjbradley** [comment]
The margin on the `<body>` should probably be `0`.

If you don’t have an Issues tab on the other repository got to the "Settings" tab and scroll down a little—you can turn Issues on there.
